config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get "users#show"
  devise_for :users
  root to: 'events#index'

  resources :events
  resources :users, only: [:show]
  resources :event_attendees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# rubocop:disable all

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_attendees, foreign_key: :attended_event_id, dependent: :delete_all
  has_many :attendees, through: :event_attendees, source: :event_attendee
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  validates :event_date, presence: true
  validates :event_name, presence: true

  # scope :past, -> { order(:event_date).where('event_date < ?', Date.today) }
  # scope :upcoming, -> { order(:event_date).where('event_date < ?', Date.today) }
  scope :upcoming_events, -> { order(:event_date).where('event_date >= ?', Time.zone.now) }
  scope :previous_events, -> { order(:event_date).where('event_date < ?', Time.zone.now) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'

  validates :event_attendee, uniqueness: { scope: :attended_event }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :event_attendees, foreign_key: :event_attendee_id, dependent: :delete_all
  has_many :attended_event, through: :event_attendees
  has_many :created_events, foreign_key: 'user_id', class_name: 'Event', dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendees_controller.rb
# rubocop:disable all

class EventAttendeesController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  def new
    @event_attendee = EventAttendee.new
    @event = Event.new
  end

  def create
    @event_attendee = EventAttendee.new(event_attendee_params)

    if @event_attendee.save
      redirect_to request.referrer, notice: 'You are attending this event!'
    else
      render :new
    end
  end

  def destroy
    @event_attendee.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'You are not attending this anymore.' }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event_attendee = EventAttendee.find(params[:id])
  end

  def event_attendee_params
    params.require(:event_attendee).permit(:attended_event_id, :event_attendee_id)
  end
end

# rubocop:enable all

app/controllers/events_controller.rb
# rubocop:disable all

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index    
    @past_events = Event.previous_events
    @upcoming_events = Event.upcoming_events

    @event_attendee = EventAttendee.new
  end

  def new
    @event = current_user.created_events.build
    #@event = Event.new
    @event_attendee = EventAttendee.new
  end

  def edit
    @event = Event.find(params[:id])
  end
  
  def show
    @users = User.all

    @event_attendees = EventAttendee.all
    @event_attendee = EventAttendee.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    #@event = Event.new(event_params)
    @creator = @event.build_creator(id: current_user.id, email: current_user.email)

    if @event.save
      redirect_to user_path(current_user), notice: 'Your event was created'
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to user_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end
  
#  def Event.upcoming_events
#    order(:event_date).where('event_date >= ?', Time.zone.now)
#  end

#  def Event.previous_events
#    order(:event_date).where('event_date < ?',  Time.zone.now)
#  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:event_name, :event_date, :user_id)
  end
end

app/controllers/users_controller.rb
# rubocop:disable all

class UsersController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def show
    @created_events = current_user.created_events
    @past_events = current_user.attended_event.previous_events
    @upcoming_events = current_user.attended_event.upcoming_events
    
    @users = User.all
    @events_attendees = EventAttendee.all
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to user_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find_by(params[:user_id])
  end
end

app/helpers/application_helper.rb
# rubocop:disable all

module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
# rubocop:disable all

module EventAttendeesHelper
end

app/helpers/events_helper.rb
# rubocop:disable all

module EventsHelper
end

app/helpers/users_helper.rb
# rubocop:disable all

module UsersHelper
end

app/views/event_attendees/_form.html.erb
<%= form_with model: @event_attendee, local: true do |f| %>
  <div class="mb-3">
    <%= f.number_field :attended_event_id, value: @id, class: "form-control", type: :hidden %>
  </div>

  <div class="mb-3">
    <%= f.number_field :event_attendee_id, value: current_user.id, class: "form-control", type: :hidden %>
  </div>

  <%= f.submit "Attend Event", class: "btn btn-primary btn-sm" %>
<% end %>

app/views/event_attendees/index.html.erb
<h1>Hello this is ateendees page index</h1>

<ul class="list-group">
  <% @event.attendees.find_each do |attendee| %>
      <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-action list-group-item-secondary">
          <%= attendee.email %> | 
          <%= attendee.email %>
      </li>
  <% end %>
</ul>

app/views/event_attendees/new.html.erb
<h1>Accept attend Event</h1>

<%= render 'event_attendees/form' %>

app/views/event_attendees/show.html.erb
<h1>show attend Event</h1>

app/views/events/_form.html.erb
<%= form_with model: @event, class:"row g-3", local: true do |f| %>
  <div class="col-md-2">
    <%= f.date_field :event_date, placeholder: "Event date", class: "form-control" %>
  </div>
  <div class="col-md-10">
    <%= f.text_field :event_name, placeholder: "Event name", class: "form-control" %>
    <%= f.number_field :user_id, id: :event_user_id, value: current_user.id, class: "form-control", type: :hidden %>
  </div>
  <div class="col-12">
    <%= f.submit class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1 class="text-primary py-2">Edit Event</h1>

<div class="container my-2">
  <%= render "form", event: @event %>
</div>

<div class="container my-2">
  <%= link_to "Back", :back, class:"btn btn-dark" %>
</div>

app/views/events/index.html.erb
<h1 class="text-primary py-2">Upcoming Events:</h1>
  <% @upcoming_events.each do |event| %>
    <div class="card my-2">
      <div class="card-header">
        <%= event.event_date %>
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p><%= link_to event.event_name, event_path(event)%></p>  
          <% if user_signed_in? %>       
          <footer class="blockquote-footer"><cite title="Source Title"><%= event.creator.email %></cite></footer>
          <% end %>
        </blockquote>
      </div>

      <div  class="card-footer">
        <% if user_signed_in? %>
          <% attend = EventAttendee.find_by(attended_event: event.id, event_attendee: current_user) %>
          <% if attend %>
            <%= button_to('Unattend Event!', event_attendee_path(id: attend.id, attended_event: event.id), method: :delete, class: "btn btn-secondary btn-sm") %>
          <% else %>
            <% @id = event.id %>
            <%= render 'event_attendees/form' %>
          <% end %>
        <% end %>
        
      </div> 
    </div>
  <% end %>

  <h2 class="text-secondary py-3">Previous Events:</h2>

<% @past_events.each do |event| %>
    <div class="card my-2">
      <div class="card-header">
        <%= event.event_date %>
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p><%= link_to event.event_name, event_path(event)%></p>
          <% if user_signed_in? %> 
          <footer class="blockquote-footer"><cite title="Source Title"><%= event.creator.email %></cite></footer>
          <% end %> 
        </blockquote>
      </div>

      <div  class="card-footer">
        <% if user_signed_in? %>
          <% attend = EventAttendee.find_by(attended_event: event.id, event_attendee: current_user) %>
          <% if attend %>
            <%= button_to('Unattend Event!', event_attendee_path(id: attend.id, attended_event: event.id), method: :delete, class: "btn btn-secondary btn-sm") %>
          <% else %>
            <% @id = event.id %>
            <%= render 'event_attendees/form' %>
          <% end %>
        <% end %>
      </div> 
    </div>
  <% end %>

app/views/events/new.html.erb
<h1 class="text-primary py-2">Create New Event</h1>

<div class="container my-2">
  <%= render 'form' %>
</div>

<div class="container my-2">
  <%= link_to "Back", root_path, class:"btn btn-dark" %>
</div>

app/views/events/show.html.erb
<h1 class="text-primary py-2">Event Info</h1>

<div class="card my-2">
  <h5 class="card-header text-secondary"><strong>Event: </strong><%= @event.event_name %></h5>
  <div class="card-body">
    <h5 class="card-title text-secondary"><strong>Date: </strong><%= @event.event_date %></h5>
    <p class="card-text text-secondary">Text information of event</p>
    <% if user_signed_in? %>
      <% attend = EventAttendee.find_by(attended_event: @event.id, event_attendee: current_user) %>
      <% if attend %>
        <%= button_to('Unattend Event!', event_attendee_path(id: attend.id, attended_event: @event.id), method: :delete, class: "btn btn-secondary btn-sm") %>
      <% else %>
        <% @id = @event.id %>
        <%= render 'event_attendees/form' %>
      <% end %>
  </div>
  <div  class="card-footer">
    <% if current_user.id == @event.creator.id %>
    <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
    <%= link_to "Edit", edit_event_path(@event), class:"btn btn-outline-warning" %>
    <% end %>
    <% end %>
  </div>
</div>

<h2 class="text-secondary py-2">List of attendees to this event:</h2>

<ul class="list-group">
  <% @event.attendees.distinct.find_each do |attendee| %>
      <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-action list-group-item-secondary">
          <%= attendee.email %>
      </li>
  <% end %>
</ul>

<div class="container my-2">
  <%= link_to "Back", root_path, class:"btn btn-dark" %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Private Events", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", root_path, class:"nav-link" %>
        <% if user_signed_in? %>
          <%= link_to "My Events", user_path(current_user), class: "nav-link" %>
          <%= link_to "New Event", new_event_path, class: " btn btn-primary" %>    
        <% end %>
      
      </div>
    </div>

    <ul class="nav nav-tabs">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>

      <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-info">

    <div class="container bg-light my-2 py-2">
      <% if flash[:notice] %>
        <div class="alert alert-primary alert-dismissible fade show my-1" role="alert">
          <strong><%= notice %></strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible fade show my-1" role="alert">
          <strong><%= alert %></strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= render 'layouts/header' %>

    </div>

    <div class="container bg-light my-3 p-3">
      <%= yield %>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/show.html.erb
<h1 class="text-primary py-2">My Events:</h1>

  <% @created_events.order(:event_date).each do |event| %>
    <% if current_user.id == event.user_id %>
      <div class="card my-2">
        <div class="card-header">
          <%= event.event_date %>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p><%= link_to event.event_name, event_path(event)%></p>         
            <footer class="blockquote-footer"><p>Event information</p></footer>
          </blockquote>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
          <%= link_to "Edit", edit_event_path(@event), class:"btn btn-outline-warning" %>
        </div>
      </div>
    <% end %>
  <% end %>

<h3 class="text-secondary py-2">Events to attend:</h3>

<h4 class="text-dark py-2">Uncoming events</h4>

<div class="container bg-light my-2 py-2">
<ul class="list-group">
  <% @upcoming_events.distinct.find_each do | attendee | %>

      <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-action list-group-item-secondary">
        <div class="ms-2 me-auto">
          <div class="fw-bold"><%= link_to attendee.event_name, event_path(attendee) %></div>
          <%= attendee.event_date %>
        </div>
      </li>

  <% end %>
</ul>
</div>

<h4 class="text-dark py-2">Past events</h4>

<div class="container bg-light my-2 py-2">
<ul class="list-group">
  <% @past_events.distinct.find_each do | attendee | %>

      <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-action list-group-item-secondary">
        <div class="ms-2 me-auto">
          <div class="fw-bold"><%= link_to attendee.event_name, event_path(attendee) %></div>
          <%= attendee.event_date %>
        </div>
        <%# link_to "Unnattend", root_path, class:"btn btn-primary btn-small" %>
      </li>

  <% end %>
</ul>
</div>
    
<div class="container my-2">
  <%= link_to "Back", :root, class:"btn btn-dark" %>
</div>